# Generated by Django 5.1.2 on 2024-11-03 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=100)),
                (
                    "dishes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dishes.foodmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["restaurant_name"],
            },
        ),
    ]
